# Generated by Django 5.2.12 on 2026-03-20 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="название")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="базовая цена"
                    ),
                ),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(
                        verbose_name="ориентировочное время (мин)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
            ],
            options={
                "verbose_name": "зона доставки",
                "verbose_name_plural": "зоны доставки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CourierShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="дата")),
                ("start_time", models.TimeField(verbose_name="начало смены")),
                ("end_time", models.TimeField(verbose_name="конец смены")),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="курьер",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shifts",
                        to="delivery.deliveryzone",
                        verbose_name="зона",
                    ),
                ),
            ],
            options={
                "verbose_name": "смена курьера",
                "verbose_name_plural": "смены курьеров",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
