# Generated by Django 5.2.12 on 2026-03-20 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("delivery", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("paid", "Оплачен"),
                            ("assembling", "Сборка"),
                            ("assembled", "Собран"),
                            ("delivering", "Доставка"),
                            ("delivered", "Доставлен"),
                            ("completed", "Завершён"),
                            ("cancelled", "Отменён"),
                            ("refunded", "Возврат"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                ("delivery_date", models.DateField(verbose_name="дата доставки")),
                (
                    "delivery_time_slot",
                    models.CharField(
                        choices=[
                            ("09-12", "09:00–12:00"),
                            ("12-15", "12:00–15:00"),
                            ("15-18", "15:00–18:00"),
                            ("18-21", "18:00–21:00"),
                        ],
                        max_length=20,
                        verbose_name="время доставки",
                    ),
                ),
                ("delivery_address", models.TextField(verbose_name="адрес доставки")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="итоговая цена"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("paid", "Оплачено"),
                            ("refunded", "Возвращено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="статус оплаты",
                    ),
                ),
                (
                    "photo_before_delivery",
                    models.ImageField(
                        blank=True,
                        upload_to="deliveries/",
                        verbose_name="фото перед доставкой",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="заметки")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Сайт"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("phone", "Телефон"),
                            ("instagram", "Instagram"),
                        ],
                        default="website",
                        max_length=20,
                        verbose_name="источник",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "assigned_courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courier_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="курьер",
                    ),
                ),
                (
                    "assigned_florist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="florist_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="флорист",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="customers.customer",
                        verbose_name="клиент",
                    ),
                ),
                (
                    "delivery_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="delivery.deliveryzone",
                        verbose_name="зона доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="количество"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="цена за единицу"
                    ),
                ),
                (
                    "bouquet_recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.bouquetrecipe",
                        verbose_name="техкарта букета",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "позиция заказа",
                "verbose_name_plural": "позиции заказа",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(max_length=20, verbose_name="старый статус"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=20, verbose_name="новый статус"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время изменения"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="комментарий")),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="изменил",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="orders.order",
                        verbose_name="заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог статуса заказа",
                "verbose_name_plural": "логи статусов заказов",
                "ordering": ["-changed_at"],
            },
        ),
    ]
