# Generated by Django 5.2.12 on 2026-03-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "all_channels",
                    models.JSONField(
                        default=dict,
                        help_text="telegram, whatsapp, instagram handles",
                        verbose_name="каналы связи",
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        default=dict,
                        help_text="allergies, fav_flowers, color_palette",
                        verbose_name="предпочтения",
                    ),
                ),
                (
                    "memorable_dates",
                    models.JSONField(
                        default=list,
                        help_text="[{date, description, reminder_days_before}]",
                        verbose_name="памятные даты",
                    ),
                ),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("regular", "Постоянный"),
                            ("vip", "VIP"),
                            ("churned", "Отток"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="сегмент",
                    ),
                ),
                (
                    "bonus_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="бонусный баланс",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="заметки")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
                "ordering": ["-created_at"],
            },
        ),
    ]
