# Generated by Django 5.2.12 on 2026-03-20 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BouquetRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="название")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "packaging",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="упаковка"
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="стоимость работы",
                    ),
                ),
                (
                    "margin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=30,
                        max_digits=5,
                        verbose_name="наценка (%)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активный"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="bouquets/", verbose_name="изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "техкарта букета",
                "verbose_name_plural": "техкарты букетов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="название")),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="категория"),
                ),
                (
                    "default_unit",
                    models.CharField(
                        default="stem", max_length=20, verbose_name="единица измерения"
                    ),
                ),
            ],
            options={
                "verbose_name": "цветок",
                "verbose_name_plural": "цветы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="название")),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
            ],
            options={
                "verbose_name": "поставщик",
                "verbose_name_plural": "поставщики",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BouquetComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="количество")),
                (
                    "unit",
                    models.CharField(
                        default="stem", max_length=20, verbose_name="единица измерения"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_components",
                        to="inventory.bouquetrecipe",
                        verbose_name="техкарта",
                    ),
                ),
                (
                    "flower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.flower",
                        verbose_name="цветок",
                    ),
                ),
            ],
            options={
                "verbose_name": "компонент букета",
                "verbose_name_plural": "компоненты букета",
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="bouquetrecipe",
            name="components",
            field=models.ManyToManyField(
                through="inventory.BouquetComponent",
                to="inventory.flower",
                verbose_name="компоненты",
            ),
        ),
        migrations.CreateModel(
            name="FlowerBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_date", models.DateField(verbose_name="дата поступления")),
                ("expiry_date", models.DateField(verbose_name="срок годности")),
                ("quantity", models.PositiveIntegerField(verbose_name="количество")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="цена за единицу"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "В наличии"),
                            ("low_stock", "Мало"),
                            ("expired", "Истёк срок"),
                            ("depleted", "Израсходовано"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "flower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="inventory.flower",
                        verbose_name="цветок",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="inventory.supplier",
                        verbose_name="поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "партия цветов",
                "verbose_name_plural": "партии цветов",
                "ordering": ["arrival_date"],
            },
        ),
        migrations.CreateModel(
            name="WriteOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="количество")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("wilted", "Увяли"),
                            ("damaged", "Повреждены"),
                            ("defective", "Брак"),
                            ("expired", "Истёк срок"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="причина",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="заметки")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="write_offs",
                        to="inventory.flowerbatch",
                        verbose_name="партия",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="выполнил",
                    ),
                ),
            ],
            options={
                "verbose_name": "списание",
                "verbose_name_plural": "списания",
                "ordering": ["-created_at"],
            },
        ),
    ]
