# Generated by Django 5.2.12 on 2026-03-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquetrecipe",
            name="cached_selling_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="кэшированная цена продажи",
            ),
        ),
    ]
